name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script_stop: true
        script: |
          cd BackEnd
          git pull
          killall python3
          if [ $? -eq 0 ]; then
            echo "Process killed successfully."
          else
            echo "Error: Failed to kill the process."
            exit 1
          fi
            
          python main.py          
