name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$EC2_SSH_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -o StrictHostKeyChecking=no -r . $EC2_USER@$EC2_HOST:/path/to/deploy/directory
        # 원한다면 ssh를 사용해 추가 명령어를 EC2에서 실행
        # 예: 서버 재시작, 종속성 설치 등
        ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'your-command-here'
        rm -f private_key.pem
