name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$EC2_SSH_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp "BE-dev.pem" ec2-user@ec2-54-180-76-116.ap-northeast-2.compute.amazonaws.com:/API/
        ssh -i "BE-dev.pem" ec2-user@ec2-54-180-76-116.ap-northeast-2.compute.amazonaws.com 'python /API/main.py'
        rm -f private_key.pem
