name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script_stop: true
        script: |
          cd BackEnd
          git pull
          if sudo netstat -tuln | grep -q ':8080 '; then
            echo "server reload"
          else
            echo "server start"
            python main.py &
          fi
