name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH and deploy
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        # Install SSH client
        sudo apt-get update
        sudo apt-get install -y openssh-client

        # Save private key to file
        echo "$PRIVATE_KEY" > BE-dev.pem
        chmod 600 BE-dev.pem

        # SSH into the EC2 instance, clone the repo, and run main.py
        ssh -i BE-dev.pem ec2-user@ec2-54-180-76-116.ap-northeast-2.compute.amazonaws.com <<EOF
          git clone git@github.com:MZ-and-DMZ/BackEnd.git
          cd BackEnd
          python3 main.py
EOF
